### ISSUE TITLE
Transfer SCAI predicate APIs/tooling and demos into in-toto org

### ISSUE THREAD

**Issue by marcelamelara** [in-toto/community#11]
Hello!

I've been implementing CLI tools for generating/verifying [SCAI predicate](https://github.com/in-toto/attestation/blob/main/spec/predicates/scai.md) metadata, as well as implementing a number of example use cases. This implementation includes Go and Python APIs for generation, and Go APIs that were modeled to fit with the [ITE-10/11 in-toto-attestation-verifier](https://github.com/adityasaky/in-toto-attestation-verifier) that @adityasaky has been implementing. 

Everything can be found at: https://github.com/IntelLabs/supply-chain-attribute-integrity/

From discussions with @SantiagoTorres about this work, we think the in-toto org would be a great home for this repo. While the tools currently focus on SCAI, they hopefully also facilitate completing the transition to ITE-6/ITE-9 in in-toto-python and in-toto-golang.

I'd appreciate any and all feedback from the community about this transfer. Thanks!

**Comment by SantiagoTorres** [comment]
Hi, I want to second that I'd like to move this forward. Let's discuss this during the community meeting and timeline this (I personally don't think there are any blockers).

**Comment by marcelamelara** [comment]
hello! I wanted to nudge this issue. This donation was discussed at the [Sep 2023 community meeting](https://github.com/in-toto/community/blob/main/community-meetings/2023.md#scai-predicate-donation); there didn't seem to have been any major blockers, but also no timeline was discussed. Is there anything that needs to happen on my end to help reach a resolution?

**Comment by trishankatdatadog** [comment]
Sorry for the delay. Great idea, and fine by me! As long as we have enough maintainers for the new repo, we should be good to go

**Comment by marcelamelara** [comment]
Thanks @trishankatdatadog ! I can certainly act as a maintainer for this repo, though it would also be great to have one or two additional maintainers to work with.

**Comment by trishankatdatadog** [comment]
> Thanks @trishankatdatadog ! I can certainly act as a maintainer for this repo, though it would also be great to have one or two additional maintainers to work with.

Sounds good. Please determine whom these additional maintainers will be, and we'll go from there. Thanks!

**Comment by marcelamelara** [comment]
@adityasaky and @SantiagoTorres, can you please confirm that you agree to act as maintainers for this new repo? After the KubeCon NA '23 demo is finalized, we don't expect much churn in this repo.

**Comment by adityasaky** [comment]
Confirmed, happy to help out as a third maintainer given my current time constraints. But as I understand the purpose of this repo, that should be fine.

**Comment by marcelamelara** [comment]
@pxp928 Could you please confirm that you've also agreed to act as a fourth maintainer for this repo? We should have enough coverage :)

**Comment by pxp928** [comment]
> @pxp928 Could you please confirm that you've also agreed to act as a fourth maintainer for this repo? We should have enough coverage :)

Yes confirmed.

**Comment by SantiagoTorres** [comment]
Hii, so we have three people? I'm also willing to help maintain (the more the merrier!)

**Comment by colek42** [comment]
Approved!

**Comment by marcelamelara** [comment]
Thank you all! It seems like the remaining question is what to name this repo once it's part of in-toto. Besides leaving it as "supply-chain-attribute-integrity" other options may be "scai-apis" or "scai-demos". Personally, I think "scai-demos" signals the long-term intent as the plan I think is to upstream the relevant ITE-9/10/11 APIs into in-toto(-golang), but I truly don't have particularly strong feelings one way or another. Thoughts on naming?

**Comment by JustinCappos** [comment]
I approve moving this forward.

**Comment by marcelamelara** [comment]
Ok, so if we're ready to move this forward. I'll set up a transfer for this repo as "scai-demos".

**Comment by marcelamelara** [comment]
Now at https://github.com/in-toto/scai-demos ! Thank you all!
