### ISSUE TITLE
Transfer in-toto-attestation-verifier to in-toto org

### ISSUE THREAD

**Issue by adityasaky** [in-toto/community#14]
I've been working on a prototype implementation of ITEs 10 and 11. Currently, this lives in my GitHub namespace: https://github.com/adityasaky/in-toto-attestation-verifier.

I propose moving this prototype to the in-toto namespace for further development, likely as https://github.com/in-toto/attestation-verifier. I've discussed with @marcelamelara about helping co-maintain the verifier until it's ready to be archived and integrated into other in-toto implementations.

**Comment by marcelamelara** [comment]
Yes, confirming that I can co-maintain this ITE-10/11 verifier prototype.

**Comment by adityasaky** [comment]
This transfer is complete!
