### ISSUE TITLE
Donation of Witness, Archivista, and related repositories

### ISSUE THREAD

**Issue by jkjell** [in-toto/community#15]
Hello in-toto community! 👋 

 TestifySec (@colek42, @mikhailswift, and myself) would like to propose the donation of [Witness](https://github.com/testifysec/witness) 🦉 & [Archivista](https://github.com/testifysec/archivista) :shipit: to the in-toto project.

 As a company, we are committed to open source software and the success of the in-toto project.  We believe that the donation of these projects can help enable experimentation, development, and adoption of in-toto as the industry standard framework for creating and validating attestations.

 In alignment with our "default open" approach to developing software, we're making this proposal before these projects are perfect. I will keep a list of outstanding issues to resolve and follow up tasks below, based on feedback from the community and ITSC. 

 Additionally, in light of our company's sponsorship of these projects, we'd also like to ensure the community and ITSC's review of the [governance](https://github.com/in-toto/community/blob/main/GOVERNANCE.md) model, as it applies to these projects. There are no outstanding gaps that I see but, we want the continued development of these projects to be above board and in alignment with the highest standards of the CNCF and in-toto project.

 Thank you for your consideration and feedback. 🙇‍♂️ 

## 👇 Additional background below 👇 

 Without going into extreme detail of each project, I'd like to highlight how I see Witness and Archivista accomplishing the above goal of enabling the continued success of the in-toto project.

### Witness
 Witness is a pluggable framework for supply chain security, enabled by an attestor model to create in-toto attestations. Witness attestors are pieces of code that assert facts about a system and store those facts in a versioned schema. The attestors follow a [lifecycle](https://github.com/testifysec/witness#attestor-life-cycle) that can coordinate the ordering and creation of predicates during the observation of a command.

 The pluggable model of attestors enables experimentation with new predicate types by allowing an implementation to focus on the predicate details to be gathered, and not the common code required to implement a DSSE envelope, signing of that envelope with different key providers, or instrumenting a command to be observed.  From a consumer perspective, `witness` can be used without enabling the attestors that are in a state of experimentation or development.

 This attestation model can also be verified by a Witness [policy](https://github.com/testifysec/witness#verification-lifecycle). While this model may be slightly diverged from ITE-10 and ITE-11, we plan to soon align with @adityasaky's  [in-toto-attestation-verifier](https://github.com/adityasaky/in-toto-attestation-verifier/).

### Archivista
 If an attestation is created but, never verified, is it really an attestation? As the amount of supply chain metadata continues to increase, the management of those attestations becomes a harder problem to manually solve. There's no way around  the need of the attestations created by a supply chain to verify a policy written for that supply chain. 

 Archivista is our proposed solution to that problem. This solution is constrained to the problem-space of storing and retrieving attestations. When attestations are stored, a graph is created based on the predicate-type and subjects of that attestation. This allows the validation of a policy, without having to specify each and every attestation that was created for an artifact.

 This solution may not be an one-size-fits-all encompassing solution but, it will enable for iteration on more complex policies that combine multiple attestations and layouts without an excessive burden on a consumer. TestifySec operates a publicly available instance of Archivista [here](https://archivista.testifysec.io/).

### Related Projects
 A list of related project summaries can be found on our [community page](https://github.com/testifysec/community#projects-overview). The repositories range from "Getting Started" guides to showcases of advanced uses of in-toto attestations. The advanced use-cases include:
* a Witness Github Action for creating attestations during a Github Actions workflow
* a Gatekeeper external data provider to enable admission control of container images based on policy compliance

## Outstanding Issues to Resolve ✅ 

- [x] Communication of proposal during in-toto community call
- [ ] License and Copyright review of all projects
- [ ] Establishment of project maintainers across multiple companies/organizations
- [ ] ITSC Approval

**Comment by JustinCappos** [comment]
I propose that Witness and Archivista be considered separately.  Can we disentangle them and resubmit as separate issues?
