### ISSUE TITLE
Donation of witness and go-witness 

### ISSUE THREAD

**Issue by jkjell** [in-toto/community#17]
This is a related issue to https://github.com/in-toto/community/issues/15:
- Witness Repository: https://github.com/testifysec/witness 
- Go-Witness Repository: https://github.com/testifysec/go-witness

Following the guidance of the ITSC, we'd like this issues to serve as the record of the ITSC's vote and the follow up actions required for and following the donation:

- [x] A majority of the ITSC members vote to accept the donation.
- [ ] Labeling of the witness and go-witness libraries as experimental (or according to a future maturity model developed by the ITSC).
- [ ] That label can be reviewed once the code of these repositories comes in line with the ITE's described [here](https://github.com/in-toto/ITE) and once the ITSC formalizes the sub-project maturity model.

**Comment by JustinCappos** [comment]
I vote to accept!

**Comment by trishankatdatadog** [comment]
Do we have a list of maintainers?

**Comment by colek42** [comment]
I am abstaining from the vote due to a conflict

**Comment by jkjell** [comment]
> Do we have a list of maintainers?

Added here: https://github.com/testifysec/witness/blob/main/MAINTAINERS.md and https://github.com/testifysec/go-witness/blob/main/MAINTAINERS.md

**Comment by trishankatdatadog** [comment]
Accepting!

**Comment by 06kellyjac** [comment]
I vote to accept

**Comment by JustinCappos** [comment]
Given the majority of accept votes from ITSC members, Witness and go-witness are now officially subprojects of in-toto!

**Comment by JustinCappos** [comment]
I will close this as completed.  We will address the labeling of projects as a separate, holistic issue (#19).
