### ISSUE TITLE
Donation of Archivista

### ISSUE THREAD

**Issue by jkjell** [in-toto/community#18]
This is a related issue to https://github.com/in-toto/community/issues/15:
- Archivista Repository: https://github.com/testifysec/archivista

Following the guidance of the ITSC, we'd like this issues to serve as the record of the ITSC's vote and the follow up actions required for and following the donation:

- [x] A majority of the ITSC members vote to accept the donation.
- [ ] Labeling of archivista as experimental (or according to a future maturity model developed by the ITSC).
- [ ] That label can be reviewed once the ITSC formalizes the sub-project maturity model.

**Comment by JustinCappos** [comment]
I vote to accept this donation!

**Comment by colek42** [comment]
I am abstaining from the vote due to a conflict

**Comment by trishankatdatadog** [comment]
Do we have a list of maintainers?

**Comment by jkjell** [comment]
> Do we have a list of maintainers?

Added here: https://github.com/testifysec/archivista/blob/main/MAINTAINERS.md

**Comment by trishankatdatadog** [comment]
Accepting!

**Comment by 06kellyjac** [comment]
I vote to accept

**Comment by JustinCappos** [comment]
Given the majority of accepting votes from the ITSC, Archivista is now officially a subproject of in-toto!

**Comment by JustinCappos** [comment]
I will close this as completed.  We will address the labeling of projects as a separate, holistic issue (#19).
