### ISSUE TITLE
Exclude adopter from CLOMonitor check

### ISSUE THREAD

**Issue by matglas** [in-toto/community#23]
There is an exemptions option for CLO Monitor and I think we could exclude the adopters check because why would we need to mention adopters on the community repo. 😄 

For reference this is how its done: https://github.com/cncf/clomonitor/blob/main/docs/metadata/.clomonitor.yml

Mention the check and the reason.

**Comment by adityasaky** [comment]
Can we point to in-toto/friends?

**Comment by matglas** [comment]
Yes that could be a good reference for community adopter. Good suggestion!

**Comment by matglas** [comment]
@adityasaky I created a PR with this small addition. Would you be able to review it?

**Comment by adityasaky** [comment]
I do not have maintainer bit on this repository anymore. I've flagged the ITSC over on slack to take a look.
