### ISSUE TITLE
Develop a  reference doc contribution policy

### ISSUE THREAD

**Issue by jbogarthyde** [in-toto/community#28]
*UPDATE 05/27/2024 (transfer issue from in-toto/docs)*

   - [ ] Specify how and where developers provide reference docs for new implementations. 
   Reference documentation should go with the implementation repo in GitHub, with sources and generation information in a *doc* subdirectory. 
   - [ ] Specify what to document for an implementation. 
   Use the Python Reference Implementation's reference docs to see what needs to be documented. 
   These are generated using source files and a makefile in the implementation's  [*doc* subdirectory](https://github.com/in-toto/in-toto/tree/develop/doc:). 
   - [ ] Add the policy to https://github.com/in-toto/community/blob/main/CONTRIBUTING.md

**Comment by lukpueh** [comment]
> ... with sources and generation information in a doc subdirectory.

There might be programming language-specific best practices for setting up reference documentation.

I think we don't need a policy for where a subproject hosts there docs, but instead recommend that a link to the docs should be included in project wide docs.

**Comment by Ayush9026** [comment]
@lukpueh sir will raise PR for this issue.

**Comment by DarikshaAnsari** [comment]
@lukpueh doc subdirectory link is broken
