### ISSUE TITLE
in-toto Helm Charts

### ISSUE THREAD

**Issue by kairoaraujo** [in-toto/community#34]
Hi folks,

I want to propose the creation of a repository in in-toto GitHub Organization helm-charts .
Also, this project should have a branch gh-pages pointing to https://in-toto.org/helm-charts, and we could use the [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action) to automatically manage release versions of the chart.
All sub-projects that provide containers and would like to use a helm chart for deployment could use it to facilitate provisioning.
So, users could easily do:

```
helm repo add in-toto https://in-toto.io/helm-charts

helm search repo in-toto
```
I'm asking because I would like to have the Archivista helm charts released and delivered in this way :slightly_smiling_face:
So, Archivista users could have the helm charts in an easier way.

Reference:
I also managed this for [RSTUF, providing the helm-charts that way](https://repository-service-tuf.github.io/helm-charts/). So, I would love to kick off it with Archivista in the in-to-helm charts.

### Actions required:

* repository creation helm-charts
  - create the branch gh-pages
* configure the helm-charts repository Pages ( settings > Pages )
  - Build and deployment
     - Branch: gh-pages /root

Having it, I'm ready to submit the PRs to the repository and branches :wink:

**Comment by jkjell** [comment]
@in-toto/in-toto-steering-committee-itsc 

As a maintainer of Witness and Archivista, I'm happy to also be a maintainer of this new repo.

**Comment by kairoaraujo** [comment]
Hey folks, any update about this issue?

We have an issue related to this helm chart.
https://github.com/in-toto/archivista/issues/412

**Comment by SantiagoTorres** [comment]
Discussed in the community meeting!

Created @in-toto/helm-charts team and [helm-charts](https://github.com/in-toto/helm-charts) repository
